export const aiAnalyticsData = [
  {
    title: "🔊 YELLOW FRIDAY is here!",
    body: "THE CRAZIEST SALE OF THE YEAR has finally arrived 🥳 Get up to 80% off all you need 🛒🏃‍♀️",
    impressions: "4,730,902",
    tapRate: "92%",
  },
  {
    title: "Fashion SALE 💰",
    body: "Upgrade your wardrobe with up to 75% off Adidas, Reserved, Trendyol & more brands! 🛍️",
    impressions: "4,200,128",
    tapRate: "90%",
  },
  {
    title: "Flash SALE time 🥳",
    body: "From 4 to 7 PM ⌛Shop our home & kitchen selection and get an extra 10% off, up to $100! Use code: FLASH10",
    impressions: "4,310,981",
    tapRate: "90%",
  },
  {
    title: "Fashion FLASH SALE 🤩",
    body: "Crazy prices from 3 to 12 on all your fav brand 🛍️ Get an extra 10% off, up to $100 using code: FLASH10",
    impressions: "3,994,477",
    tapRate: "90%",
  },
  {
    title: "Up to 75% OFF 😍",
    body: "Explore the widest winterwear selection from LC Waikiki, DeFacto & Adidas 🛍️ Start shopping 👀",
    impressions: "3,515,272",
    tapRate: "90%",
  },
  {
    title: "From 4 to 7 PM 👼",
    body: "Get all your baby's essentials & toys with an extra 10% off, up to $100 ☜ Use code: FLASH10",
    impressions: "783,388",
    tapRate: "87%",
  },
  {
    title: "Spend & win a car! 🤯",
    body: "Get the chance to win Chery Tiggo7 Pro when you spend 2,000 EGP or more using any card 💳",
    impressions: "2,902",
    tapRate: "85%",
  },
  {
    title: "Laptops & accessories 💻",
    body: "Get the upgrade you've been long waiting for, with up to 18-month installments at 0% interest 💸",
    impressions: "577,538",
    tapRate: "85%",
  },
  // {
  //   title: "FLASH SALE 🚨",
  //   body: "From 4 to 7 PM ONLY! Buy premium electronics & appliances at exclusive prices & get an extra 10% off, up to $100 ☜ Use code: FLASH10",
  //   impressions: "810,235",
  //   tapRate: "83%",
  // },
  // {
  //   title: "Got a credit card? 💳",
  //   body: "Enjoy installments up to 18 months at 0% interest when you pay with your credit card 🤩",
  //   impressions: "886,515",
  //   tapRate: "80%",
  // },
  // {
  //   title: "Buy 1, get 1 FREE 🤩",
  //   body: "Started preparing your home for winter coziness? ❄️ Shop our wide range of pillows & quilts at great prices!",
  //   impressions: "754,328",
  //   tapRate: "80%",
  // },
  // {
  //   title: "Mastercard Offer! 💸",
  //   body: "[brand_name] Exclusive! Get 15% off, up to $250 when you pay using your Mastercard! 🤩",
  //   impressions: "544,387",
  //   tapRate: "77%",
  // },
  // {
  //   title: "Early bird 🦅",
  //   body: "Exciting Yellow Friday deals ahead 🏃‍♀️🏃‍♂️ Up to 75% off top brands 🤯 Get shopping! 🛍️",
  //   impressions: "968,659",
  //   tapRate: "75%",
  // },
  // {
  //   title: "9HRS Flash SALE 🏃‍♀️💨",
  //   body: "10% off, up to $100, on your favorite fashion picks from 1 to 10 PM ⌛ when using the FLASH10 code! 🛒",
  //   impressions: "649,010",
  //   tapRate: "75%",
  // },
  // {
  //   title: "11.11 sale EXTENDED 😍",
  //   body: "Thought you missed it, ha? this is your LAST chance! Load up on all you need & want, for way less 🥳",
  //   impressions: "385,946",
  //   tapRate: "75%",
  // },
  // {
  //   title: "Pay & save 💳",
  //   body: "Get 20% off, up to $250 when you pay with your credit card 💸 Don't miss this, start shopping!",
  //   impressions: "589,452",
  //   tapRate: "75%",
  // },
  // {
  //   title: "Maybelline 💄",
  //   body: "Up to 30% off the latest pieces, and more at our 11.11 expectional sale 🥰 Tap to explore 👀",
  //   impressions: "393,569",
  //   tapRate: "75%",
  // },
  // {
  //   title: "Beauty FLASH SALE! 🤩",
  //   body: "Get your favs from top brands all over the world using the FLASH10 code & get extra 10% off, up to $100! 🏃‍♀️💨",
  //   impressions: "785,645",
  //   tapRate: "73%",
  // },
  // {
  //   title: "Heads up! 👋",
  //   body: "11.11 SALE ENDS TODAY! Don't waste time & start filling your cart, RIGHT NOW 🛒💨",
  //   impressions: "525,753",
  //   tapRate: "71%",
  // },
  // {
  //   title: "Garnier skincare 💆‍♀️",
  //   body: "Get $50 off when you spend $150, you read that right! 🥰 Checkout using code: DISC50",
  //   impressions: "888,579",
  //   tapRate: "70%",
  // },
  // {
  //   title: "Buy 1, get 1 FREE & more 🙋‍♀️",
  //   body: "Need to restock on all your beauty favorites? We've got you covered with the best offers & prices 😉",
  //   impressions: "271,768",
  //   tapRate: "70%",
  // },
  // {
  //   title: "8HRS FLASH SALE 🛍️",
  //   body: "From 4 to 12 fashion SALE on your fav winter bits with an extra 10% off, up to $100 😉 Use FLASH10 code ☜",
  //   impressions: "557,815",
  //   tapRate: "70%",
  // },
];
